project:
  type: website
  output-dir: ../docs 
  render:
    - "*"
    - "!*.md"

website:
  title: "Social Networks "

format:
  html:
    link-external-newwindow: true
    theme: cosmo
    css: syllabus.css
    toc: true
    output-file: "index.html"
editor: source

